# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
    ]
